version: '3'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: applicant
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
